#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "----------commit-msg hook started-----------"

npx --no-install commitlint --edit "$1"
# pnpm run commitlint -- -E "$1"

echo "----------commit-msg hook finished-----------"